### ISSUE TITLE
No default args for queries

### ISSUE THREAD

**Issue by ajnisbet** [odojs/odoql#1]
I think doing an unfiltered query returning all attributes is a common use case, especially for cheap stores like localstorage.

Currently, you have to do something like this

``` javascript
ql.query('baseLayers', {}, [])
```

It would be good to have `{}` and `[]` set as default args, so you can do

``` javascript
ql.query('baseLayers')
```

**Comment by tcoats** [comment]
The latest version of odoql has support for custom methods and chaining. Empty parameters are also handled well.
